from .user import routers as userRouters
from .comment import routers as commentRouters
from .post import routers as postRouters
from .story import routers as storyRouters
from .settings import  routers as settingRouters
from .media import routers as mediaRouters
from .auth import routers as authRouters
from .follow import routers as followRouters
from .notification import routers as notifyRoouters
from .message import routers as messageRouters
